spring:
  application:
    name: pequi-short

  datasource:
    url: jdbc:postgresql://localhost:5432/pequishortdb
    username: pequishort
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 948bd69c93866c12a1b647027404dd12cf7ccde1a76cdc1b87e28638c7d175a3
  expiration: 7200000